name: Run Spectral on Pull Requests

on:
  - push

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@6b6f6a20b4ca586f2fa276fcc5e070125da8a0de
        with:
          file_glob: 'doc/api/*.yaml'
