name: Run Spectral on Pull Requests

on:
  - push

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@018e53df2b2a045681cccc62380cd7c04cef7dec
        with:
          file_glob: 'doc/api/*.yaml'
